### ISSUE TITLE
关于侧边栏导航激活状态

### ISSUE THREAD

**Issue by bestsamcn** [wszgxa/vue-cnode#3]
你好，我在制作一个侧边栏，里面的有导航列表，跟你的项目一样的，也需要一个对应当前路由的激活状态。
现在的问题是：我在你那个sidebar.vue的组件里，看到你使用了getters:{ routeName: ({ route }) => route.name }这段代码，但是我看你vuex/modules文件夹里面根本没有route这个模块，请问下，这个route是vue-router自动挂载到store上面的吗

**Comment by wszgxa** [comment]
@bestsamcn https://github.com/vuejs/vuex-router-sync
